spring.application.name=Hawamoni
spring.datasource.url=jdbc:postgresql://aws-1-eu-north-1.pooler.supabase.com:6543/${DATABASE_NAME}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}


#JPA AND HIBERNATE CONFIGURATION
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.show_sql=true

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
spring.security.oauth2.client.registration.google.client-id=${GOOGLE-CLIENT-ID}

# Connection pool (important because Supabase has strict connection limits)
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=30000