spring.application.name=Hawamoni
spring.datasource.url=jdbc:mysql://localhost:3306/hawamoni
spring.datasource.username=root
spring.datasource.password=Henry123@#$
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


#JPA AND HIBERNATE CONFIGURATION
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
spring.security.oauth2.client.registration.google.client-id=${GOOGLE-CLIENT-ID}